---
name: '💬 Discuss'
description: Start a discussion
title: '[Discuss]: Discuss title'
labels: [discuss]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Discuss topic
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Screenshots
  - type: textarea
    id: observed-behavior
    attributes:
      label: Useful Links
